### ISSUE TITLE
Buggy behaviour in `jagged_vector_buffer` to `jagged_vector` copy for value_type whose size is 512 X N bytes 

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/vecmem#175]
`jagged_vector_buffer` to `jagged_vector` copy makes an error when the size of `jagged_vector` is larger than one and the size of element is 512 bytes or its integer multiplication:

```
unknown file: Failure
C++ exception with description "/home/beomki/projects/vecmem/vecmem/cuda/src/utils/cuda/copy.cpp:52 Failed to execute: cudaMemcpy(to_ptr, from_ptr, size, copy_type_translator[cptype]) (invalid argument)" thrown in the test body.
```

Following code is the minimal reproduction of the error. 

```c++
template <std::size_t ROWS, std::size_t COLS>
using matrix = vecmem::static_array<vecmem::static_array<double, ROWS>, COLS>;

/// 512 bytes object (double, 8x8 matrix) makes an error with buffer2 copy!
/// Any other dimension seems OK unless it is the multiple integer of 512 bytes
using value_type = matrix<8,8>;

/// Test buffers with "large" elements (for which alignment becomes important)
TEST_F(cuda_containers_test, very_large_buffer) {

    // The memory resource(s).
    vecmem::cuda::managed_memory_resource managed_resource;

    // Test a (2D) jagged vector with (2D) matrix
    vecmem::data::jagged_vector_buffer<value_type> buffer1({200},
                                                             managed_resource);
    m_copy.setup(buffer1);
    vecmem::jagged_vector<value_type> buffer1_host(&managed_resource);
    
    /// This is OK because the size of jagged vector is 1
    m_copy(buffer1, buffer1_host);

    // Test a (2D) jagged vector with (2D) matrix
    vecmem::data::jagged_vector_buffer<value_type> buffer2({1, 1},
                                                             managed_resource);
    m_copy.setup(buffer2);
    vecmem::jagged_vector<value_type> buffer2_host(&managed_resource);
    
    /// This is NOT OK because the size of jagged vector is larger than 1
    m_copy(buffer2, buffer2_host);
}
```

It's quite bad (or lucky) that I was playing with 8x8 matrix in detray side :/ ..

**Comment by beomki-yeo** [comment]
Similary, `matrix<float,16,8>` also makes an error

**Comment by krasznaa** [comment]
We seem to run into the same kinds of issues spookily at the same time... :ghost:

The problem here is not with any particular vector size. The problem is that you're trying to use `vecmem::cuda::copy` to copy between a host-accessible area allocated by `vecmem::cuda::managed_memory_resource`, and another host-accessible area allocated by `vecmem::host_memory_resource` / `vecmem::cuda::host_memory_resource`. (I don't see in your example which one it may be.)

I don't blame you for making this mistake, since I made the exact same mistake just yesterday with SYCL. And was treated to the same kind of error.

The the `vecmem::cuda::copy` object, as it turns out, only likes to copy between "device memory" (allocated through `vecmem::cuda::device_memory_resource`) and "something else". It is not meant for making copies from/to managed/shared memory. The whole point of managed/shared memory is that it is accessible to the host code as-is.

So... you can just use [vecmem::copy](https://github.com/acts-project/vecmem/blob/main/core/include/vecmem/utils/copy.hpp) to perform this copy. Since the [std::memcpy](https://en.cppreference.com/w/cpp/string/byte/memcpy) operations that it uses are just fine for interacting with two host-accessible pieces of memory. :wink:

See what I ended up doing in: https://github.com/acts-project/traccc/pull/170/files#diff-e44eb5d884e8a5234eab1e37d2dcc240f2df65e31e88d559a00df6e1cc7429f8R62-R66

**Comment by beomki-yeo** [comment]
Um yes it indeed works with `vecmem::copy`. Thanks a lot!
