### ISSUE TITLE
Harmonise sizes and capacities ordering in buffer creations.

### ISSUE THREAD

**Issue by guilhermeAlmeida1** [acts-project/vecmem#221]
Would be good for the user to have these two constructors use the same ordering rather than opposing ones. (I'm aware for the jagged case we're not actually using the capacities as mentioned in #95 , but regardless this would be a good change)
Could also template the `size_type` for the second one.

https://github.com/acts-project/vecmem/blob/ee210390674c9cdf3b68cddb8bc3ac61e2fe1fb4/core/include/vecmem/containers/data/jagged_vector_buffer.hpp#L104-L105

https://github.com/acts-project/vecmem/blob/ee210390674c9cdf3b68cddb8bc3ac61e2fe1fb4/core/include/vecmem/containers/data/vector_buffer.hpp#L55-L56

**Comment by krasznaa** [comment]
I agree, it was a silly mistake to implement the constructors like this. But boy will this require changing the code in a lot of places... :frowning:

Let me think about this a bit. I'm not keen on templating the `vector_buffer` constructor, since simple integer types convert into each other pretty easily. (Not like the vector types.) But I think we could come up with a slightly less error-prone interface than this current one... :thinking:

**Comment by krasznaa** [comment]
Still need to migrate all client projects to the new formalism, but this project itself now moved to a more consistent API for the two buffer types.
